services:
  app:
    build:
      context: .
      args:
        INSTALL_DEV: "true"
    container_name: app_dev
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
    command: >
      uv run uvicorn src.main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --reload-dir /app/src
    restart: unless-stopped